@startuml
sprite $keycloak [48x48/16z] {
hLK7WYCn23kG4NZd__yz9iLB2jaq9TDbIUx_lW99F4-6UO9uhWZeGqKqhq-KKFCXPn-d_X75tAHvh6W5PRThWnDt0fPgDC5RroUJohZ-g3SIDtAeoVzkQPG2
ugXQ1HS5LWApyjwYe7uONF9QPEPMC9TneS7ho-q2NY9nd8oicFvisqyYppFsyoX9xIQ-n4wSaPSWcGL2VhLk-MfcFgVJZ4xcnR3Q2NVqHU0p25NGQT03fD5F
kjeC7veOJWuzuZvVZlA-onU3HtpbKNuPeESdMn7JTz6p0H_nTys85U8K3K2JP-VOgkMnva3FbrBBitpFJqYf9RZBz_oQo02CMF8z7sP6T-OvKjv9ZcuyhF4M
pkCbRiRR_V4yPvwtESjuBhodvukDCqUUdu_FptVmBAlFh2ULX7BVG7rKhsRrhCjwiyu_kq9hkrs1ZbQbtnVwtQj_rOlrbdqru8wMM3KX2R1uFO8CUe9FiCl4
b2VOJ-0_
}
@enduml
