@startuml
sprite $opa [48x48/16z] {
xSr7biCm30JHHYPn__iwPmaSSZVfRsn9zHhuoVxHOhxf6IEoNP1HBjXGHeML1njRijkhbFDAjpzcBOnllPRpbttsYF0ySRgyhGxe2KCYxdrsXcZPYvx5Iv_T
hYEx-9u_--pt-UA0V_GPvJn0QlTSB6zCKEBxl0BjVW03SMEWljA7t_DiStt-YPxje-z6629xwRlYQ-pttZ37hhrYbfzxmpHopy02zeObmlYB_Xq1
@enduml
